# Generated by Django 4.2 on 2023-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelibrary',
            name='blur_image',
            field=models.ImageField(default=1, upload_to='blur-images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagelibrary',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
