# Generated by Django 4.2 on 2023-04-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_imagelibrary_blur_image_alter_imagelibrary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelibrary',
            name='blur_image',
        ),
    ]
