# Generated by Django 4.2 on 2023-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_imagelibrary_blur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelibrary',
            name='blur_hash',
            field=models.TextField(default='UgPZr%M{~Wxu%MWBWAt7~pt79ZRjM_t7ogRj'),
        ),
    ]
