# Generated by Django 4.2 on 2023-04-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_imagelibrary_blur_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelibrary',
            name='blur_hash',
            field=models.TextField(null=True),
        ),
    ]
