# Generated by Django 4.2 on 2023-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_imagelibrary_blur_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelibrary',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
